### ISSUE TITLE
College card spacing

### ISSUE THREAD

**Issue by TheDanMiller** [coforma/swift-tech-challenge#132]
**Describe the bug**
There is too much spacing between the card icons on the card

** Current behavior **

**To Reproduce**
1. Go the browse page, default route
2. Look at the cards
3. Play a football match on the pitch between the columns

**Expected behavior**
Card icons should have a max width and smaller uniform spacing
1. Max width 205 px (or whatever it needs to be to not have wrapping)
2. Spacing between  24px

![image](https://github.com/coforma/swift-tech-challenge/assets/7631428/76ee976b-e0bf-4656-a736-67564920f300)

## Definition of Done
[Definition of Done](https://github.com/coforma/swift-tech-challenge/blob/main/documentation/product/definition_of_done.md)

**Comment by skylerschain** [comment]
Other visual tweaks to cards: 

- On mobile card, image should be above the college name and city/state
- On desktop card, the image should be wider than it currently is
- On desktop card, the top left/bottom left corner radius needs to match top right/bottom right @ 48px
