### ISSUE TITLE
Browse page - filtering

### ISSUE THREAD

**Issue by buddhima-coforma** [coforma/swift-tech-challenge#35]
### Description
A filtering feature on the browse colleges page

### User Story
As prospective student, I want to slice and dice colleges so I can find the college(s) that fit me best

### To do
1. A button to access filters
2. Ability to add, update and remove filters
3. Indicators on which filters have been applied
4. Information on how many results are shown
5. An empty state (no results) which allows them to reset back to original state 
6. Any error states that need to be accounted for

### Acceptance Criteria
- A prospective student is able to add, change, reset filters and find the college(s) they are looking for.
- they are able to understand how filters work and which filters have been applied.

### Resources
[Mockups](https://www.figma.com/file/SGP8E3EDGxhN3vE4N74zWZ/Swift-Tech-Challenge?type=design&node-id=149-34378&mode=design&t=gHtfu2TyQsDeizJk-4)

### Definition of Done
[Definition of Done](https://github.com/coforma/swift-tech-challenge/blob/main/documentation/product/definition_of_done.md)

**Comment by ntsummers1** [comment]
Wrapped up and completed in this issue: https://github.com/coforma/swift-tech-challenge/issues/62
