### ISSUE TITLE
College details page

### ISSUE THREAD

**Issue by buddhima-coforma** [coforma/swift-tech-challenge#36]
### Description
Clicking on a college from anywhere within the website would bring up this page that shows details about a given college

### User Story
As prospective student, I want to view details for a selected college so I can figure out if it fits me or not

### Acceptance Criteria

- [ ] Page displays all the same info from card view
- [ ] User can apply from this page
- [ ] Any missing data is indicated by “Not available” 
- [ ] Page has 5 additional sections: Outcomes, Admissions, Student Body, Academics, Costs
- [ ] There are some conditional labels:
      - [ ] **Graduation rate**: If highest degree offered is Associates or below, show <4 year rate. If bach or above, show 4 year rate.
            - [ ] Note that the descriptive text also has a conditional change, noted in the mocks
      - [ ] **Retention**: If highest degree offered is Associates or below, show <4 year rate. If bach or above, show 4 year rate.
      - [ ] **SAT Scores**: The descriptive text indicates whether the SAT is required or not, noted in the mocks
      - [ ] **Average net price by HH income**: This will be a 2-column table like this one (with the same bands on the left)
![Image](https://github.com/coforma/swift-tech-challenge/assets/122126772/6a29fd93-8b0e-44c6-bd1d-5b00de0290dd)

### Resources
We're finalizing these but should be able to pull into Ready soon. See comments below + Figma.
 
### Definition of Done 
[Definition of Done](https://github.com/coforma/swift-tech-challenge/blob/main/documentation/product/definition_of_done.md)

**Comment by kristinoletmuskat** [comment]
ACs ready to go, just needs finalized mocks

**Comment by skylerschain** [comment]
Mocks have been added to the [Ready page](https://www.figma.com/file/SGP8E3EDGxhN3vE4N74zWZ/Swift-Tech-Challenge?type=design&node-id=428-31834&mode=design&t=hEqlIFuAJvinZEUd-11).

![Image](https://github.com/coforma/swift-tech-challenge/assets/95102058/d5d8ea1a-e45c-4b9d-8a26-c691a52549bb)
