### ISSUE TITLE
Application Submission + Confirmation page

### ISSUE THREAD

**Issue by buddhima-coforma** [coforma/swift-tech-challenge#74]
### Description
When an application is submitted, display this page with a confirmation message and some static content (next steps and CTAs).

### User Story
As a prospective student I can feel confident I submitted my application and clear on my next steps.

### Acceptance Criteria
- [ ] Confirmation message confirms successful submission
- [ ] The 3 next steps are listed
    - [ ] The specific college's net price calculator link works (in our data)
    - [ ] The financial aid link works
    - [ ] The FAFSA link works
    - [ ] The 'search for more schools' button works
- [ ] If the submission is not successful, user gets a separate page that has an error message with a clear CTA (doesn't have to be clickable, just something like 'try again later').
- [ ] The submissions are stored so that they can be surfaced (for a logged in user and admin etc)

### Resources
This is NOT mocked in figma -- Let us know if you need more design direction than this wireframe:
![Image](https://github.com/coforma/swift-tech-challenge/assets/122126772/05cac2b1-3be3-43af-a6c9-ce9398987a8e)

### Definition of Done
[Definition of Done](https://github.com/coforma/swift-tech-challenge/blob/main/documentation/product/definition_of_done.md)

**Comment by kristinoletmuskat** [comment]
Decision: We decided not to include email confirmation because it's time intensive (but easy, so a good follow-on).

**Comment by skylerschain** [comment]
Final mocks [here](https://www.figma.com/file/SGP8E3EDGxhN3vE4N74zWZ/Swift-Tech-Challenge?type=design&node-id=480-34049&mode=design&t=hEqlIFuAJvinZEUd-11).
