### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by buddhima-coforma** [coforma/swift-tech-challenge#75]
When there's an issue on the site, display this page with some info and an option to re-try.

AC:
- When a user faces an issue, show this page so they can know there was an issue + what they could do about it

**Comment by skylerschain** [comment]
Mocks [here](https://www.figma.com/file/SGP8E3EDGxhN3vE4N74zWZ/Swift-Tech-Challenge?type=design&node-id=480-38947&mode=design&t=hEqlIFuAJvinZEUd-11).

**Comment by buddhima-coforma** [comment]
@ntsummers1 drop a screenshot here?

**Comment by TheDanMiller** [comment]
![Image](https://github.com/coforma/swift-tech-challenge/assets/7631428/6713f39d-b997-4c11-bcab-8d4df3602779)

Current implementation
