### ISSUE TITLE
Card - no data

### ISSUE THREAD

**Issue by buddhima-coforma** [coforma/swift-tech-challenge#77]
### Description
Adding null states to card

### User Story
As a user I want to see something that makes sense if there's no data

### Acceptance Criteria

- [ ] If there is no data available for a section, show "Not Available"

### Mockups
![Image](https://github.com/coforma/swift-tech-challenge/assets/122126772/5f88161f-a75d-4b68-b244-4da4980f8038)

**Comment by TheDanMiller** [comment]
What is the final verdict on not available versus -- @buddhima-coforma @skylerschain
